### ISSUE TITLE
Doesn't work with Laravel 5.3 and laravel-elixir 6

### ISSUE THREAD

**Issue by ldelcampof** [rawcreative/laravel-elixir-babel#2]
I am using Laravel 5.3 and laravel-elixir 6 and i'm having this error:

`[12:47:55] ldelcampo:molinillos git:(master*) $ gulp                
module.js:457
    throw err;
    ^

Error: Cannot find module 'laravel-elixir/ingredients/commands/Utilities'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/laravel-elixir-babel/index.js:8:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
`

**Comment by rawcreative** [comment]
There's no need for this plugin in elixir 6 as es2015 transpiling was added in elixir 5.
